const countNounArray = [];
const countNounArrayPlural = [];
const activePassive = [];
const animInan = [];
const divineNonDivine= [];
const humanAnimalInan = [];
const mascFemNeut = [];
const mascFem = [];
const naturalArtificial = [];
const animacyClassifierArray = [];
const shapeClassifierArray = [];
const shortGenericClassifierArray = [];

countNounArray.push("acorn");
countNounArrayPlural.push("acorns");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("affliction");
countNounArrayPlural.push("afflictions");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("alder");
countNounArrayPlural.push("alders");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("divine");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tree");

countNounArray.push("anus");
countNounArrayPlural.push("anuses");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("attack");
countNounArrayPlural.push("attacks");
activePassive.push("active")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("apple");
countNounArrayPlural.push("apples");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("edible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("arch");
countNounArrayPlural.push("arches");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("tool");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("tool");

countNounArray.push("arm");
countNounArrayPlural.push("arms");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("tool");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("army");
countNounArrayPlural.push("armies");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("human");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("man");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("human2");

countNounArray.push("arrow");
countNounArrayPlural.push("arrows");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("tool");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("audience");
countNounArrayPlural.push("audiences");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("human");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("man");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("human2");

countNounArray.push("auger");
countNounArrayPlural.push("augers");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("divine");
humanAnimalInan.push("human");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("man");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("human2");

countNounArray.push("autumn");
countNounArrayPlural.push("autumns");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("divine");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("feminine2");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("axe");
countNounArrayPlural.push("axes");
activePassive.push("active")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("feminine2");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("badger");
countNounArrayPlural.push("badgers");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine2");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("land-animal");

countNounArray.push("bag");
countNounArrayPlural.push("bags");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("feminine2");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("tool");

countNounArray.push("ball");
countNounArrayPlural.push("balls");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("tool");

countNounArray.push("band");
countNounArrayPlural.push("bands");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("human");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("human2");

countNounArray.push("banquet");
countNounArrayPlural.push("banquets");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("bar");
countNounArrayPlural.push("bars");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("barrow");
countNounArrayPlural.push("barrows");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("divine");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("basket");
countNounArrayPlural.push("baskets");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("tool");

countNounArray.push("bead");
countNounArrayPlural.push("beads");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("tool");

countNounArray.push("beak");
countNounArrayPlural.push("beaks");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("beam");
countNounArrayPlural.push("beams");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("bean");
countNounArrayPlural.push("beans");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("edible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("bear");
countNounArrayPlural.push("bears");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("land-animal");

countNounArray.push("beard");
countNounArrayPlural.push("beards");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("beaver");
countNounArrayPlural.push("beavers");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("water-animal");

countNounArray.push("bed");
countNounArrayPlural.push("beds");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("bedroom");
countNounArrayPlural.push("bedrooms");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("tool");

countNounArray.push("bee");
countNounArrayPlural.push("bees");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("flying-animal");

countNounArray.push("beech");
countNounArrayPlural.push("beeches");
activePassive.push("active")
animInan.push("inan");
divineNonDivine.push("divine");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tree");

countNounArray.push("belt");
countNounArrayPlural.push("belts");
activePassive.push("active");
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("berry");
countNounArrayPlural.push("berries");
activePassive.push("passive");
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("edible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural");

countNounArray.push("bird");
countNounArrayPlural.push("birds");
activePassive.push("active");
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine21");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("flying-animal");

countNounArray.push("birdsong");
countNounArrayPlural.push("birdsongs");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("neuter");
mascFem.push("masculine21");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("blackbird");
countNounArrayPlural.push("blackbirds");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine21");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("bladder");
countNounArrayPlural.push("bladders");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("blade");
countNounArrayPlural.push("blades");
activePassive.push("active")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("blister");
countNounArrayPlural.push("blisters");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("blow");
countNounArrayPlural.push("blows");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("boar");
countNounArrayPlural.push("boars");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("land-animal");

countNounArray.push("board");
countNounArrayPlural.push("boards");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("flat");
shortGenericClassifierArray.push("tool");

countNounArray.push("boat");
countNounArrayPlural.push("boats");
activePassive.push("active")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("body");
countNounArrayPlural.push("bodies");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("bolt");
countNounArrayPlural.push("bolts");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("bone");
countNounArrayPlural.push("bones");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("book");
countNounArrayPlural.push("books");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("boot");
countNounArrayPlural.push("boots");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("bottom");
countNounArrayPlural.push("bottoms");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("boulder");
countNounArrayPlural.push("boulders");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("bow");
countNounArrayPlural.push("bows");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("naturaartificiall");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("bowl");
countNounArrayPlural.push("bowls");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("tool");

countNounArray.push("bowstring");
countNounArrayPlural.push("bowstrings");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("bracelet");
countNounArrayPlural.push("bracelets");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("tool");

countNounArray.push("brain");
countNounArrayPlural.push("brains");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("branch");
countNounArrayPlural.push("branches");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("breast");
countNounArrayPlural.push("breasts");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("breath");
countNounArrayPlural.push("breaths");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("divine");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("bristle");
countNounArrayPlural.push("bristles");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("brother");
countNounArrayPlural.push("brothers");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("human");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("man");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("human2");

countNounArray.push("brow");
countNounArrayPlural.push("brows");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("inan");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("buck");
countNounArrayPlural.push("bucks");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("land-animal");

countNounArray.push("bucket");
countNounArrayPlural.push("buckets");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("inan");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("tool");

countNounArray.push("buffet");
countNounArrayPlural.push("buffets");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("inan");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("edible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("building");
countNounArrayPlural.push("buildings");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("inan");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("bull");
countNounArrayPlural.push("bulls");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("meat");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("land-animal");

countNounArray.push("bump");
countNounArrayPlural.push("bumps");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("burden");
countNounArrayPlural.push("burdens");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("butterfly");
countNounArrayPlural.push("butterflies");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("feminine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("flat");
shortGenericClassifierArray.push("flying-animal");

countNounArray.push("cabin");
countNounArrayPlural.push("cabins");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("feminine2");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("tool");

countNounArray.push("cage");
countNounArrayPlural.push("cages");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("tool");

countNounArray.push("carp");
countNounArrayPlural.push("carps");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("feminine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("water-animal");

countNounArray.push("carrot");
countNounArrayPlural.push("carrots");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("inan");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("edible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("cat");
countNounArrayPlural.push("cats");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("anim");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("land-animal");

countNounArray.push("cauldron");
countNounArrayPlural.push("cauldrons");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("divine");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("tool");

countNounArray.push("cave");
countNounArrayPlural.push("caves");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("cavity");
countNounArrayPlural.push("cavities");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("cedar");
countNounArrayPlural.push("cedars");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("divine");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("cell");
countNounArrayPlural.push("cells");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("tool");

countNounArray.push("change");
countNounArrayPlural.push("changes");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("chariot");
countNounArrayPlural.push("chariots");
activePassive.push("active")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("tool");

countNounArray.push("cherry");
countNounArrayPlural.push("cherries");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("edible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("chicken");
countNounArrayPlural.push("chickens");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("meat");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("chickpea");
countNounArrayPlural.push("chickpeas");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("edible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("child");
countNounArrayPlural.push("children");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("human");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("child");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("human2");

countNounArray.push("chin");
countNounArrayPlural.push("chins");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("circle");
countNounArrayPlural.push("circles");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("clan");
countNounArrayPlural.push("clans");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("man");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("cliff");
countNounArrayPlural.push("cliffs");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");


"cloak",
"cloud",
"club",
"coin",
"column",
"confession",
"coot",
"corner",
"council",
"cow",
"cowherd",
"crab",
"craftsman",
"crane",
"crease",
"crime",
"crow",
"crowd",
"cuckoo",
"cup",
"curve",
"curved&nbspbeam",
"custom",
"daughter",
"dawn",
"day",
"deer",
"dent",
"dice",
"dinner",
"dip",
"direction",
"ditch",
"dog",
"dolphin",
"donkey",
"door",
"doorjam",
"dormouse",
"dorsal&nbspfin",
"dragon",
"drop",
"duck",
"eagle",
"ear",
"edge",
"eel",
"egg",
"elbow",
"elk",
"elm",
"embrace",
"emotion",
"enclosure",
"enemy",
"estuary",
"ewe",
"exchange",
"eye",
"eyebrow",
"face",
"falcon",
"family",
"father",
"favour",
"feast",
"fence",
"festival",
"field",
"finger",
"fir",
"fire",
"fish",
"fist",
"flock",
"floor",
"flower",
"fly",
"fold",
"foot",
"footprint",
"forearm",
"forehead",
"forest",
"fork",
"fort",
"fortification",
"freeman",
"friend",
"frog",
"frogspawn",
"furrow",
"garlic",
"gate",
"genocide",
"gift",
"girl",
"gland",
"glove",
"gnat",
"goat",
"god",
"goose",
"gosling",
"grain",
"granddaughter",
"grandson",
"grave",
"groove",
"grunt",
"guest",
"guitar",
"gull",
"gullet",
"gulley",
"gum",
"hall",
"hammer",
"hand",
"handle",
"hare",
"harp",
"hat",
"hawk",
"hawthorn",
"hazel",
"head",
"heart",
"hearth",
"hedgehog",
"height",
"henbane",
"herd",
"hill",
"hip",
"hole",
"home",
"honour",
"hoof",
"hook",
"horn",
"hornet",
"horse",
"horsefly",
"house",
"howl",
"hug",
"human",
"husband",
"icicle",
"insect",
"javelin",
"jaw",
"jay",
"jewel",
"journey",
"juniper",
"kernel",
"kidney",
"king",
"kiss",
"kitten",
"knee",
"knife",
"knuckle",
"lake",
"lamb",
"land",
"language",
"leaf",
"leech",
"leg",
"lever",
"limb",
"lineage",
"lion",
"lip",
"liver",
"log",
"lord",
"louse",
"lung",
"lynx",
"mace",
"maggot",
"magpie",
"mallet",
"mammoth",
"man",
"mane",
"map",
"maple",
"mare",
"married&nbspcouple",
"marsh",
"marten",
"massacre",
"master",
"meadow",
"meeting",
"membrane",
"memory",
"mistress",
"moon",
"mother",
"mountain",
"mouse",
"mouth",
"mussel",
"nail",
"name",
"navel",
"neck",
"necklace",
"needle",
"nest",
"net",
"nettle",
"night",
"noon",
"nose",
"notch",
"oak",
"oar",
"oath",
"onion",
"origin",
"orphan",
"otter",
"owl",
"ox",
"page",
"palm",
"pasture",
"path",
"paw",
"pea",
"pebble",
"peg",
"pendant",
"penis",
"perch",
"person",
"phantom",
"pick",
"pig",
"piglet",
"pike",
"pillar",
"pin",
"pit",
"place",
"plank",
"plough",
"poem",
"poet",
"point",
"pole",
"polecat",
"pool",
"poppy",
"post",
"pot",
"prayer",
"priest",
"projection",
"proverb",
"puppy",
"purchase",
"rag",
"ram",
"raven",
"ravine",
"razor",
"realm",
"reed",
"relation",
"relationship",
"rhythm",
"rib",
"right",
"ring",
"river",
"riverbank",
"road",
"rock",
"rod",
"roof",
"rooster",
"root",
"route",
"row",
"rule",
"salmon",
"saying",
"scent",
"scythe",
"sea",
"seal",
"season",
"seat",
"seed",
"serpent",
"servant",
"shaft",
"shark",
"sheep",
"sheet",
"shelf",
"shell",
"shield",
"shoe",
"shoulder",
"shroud",
"sieve",
"sign",
"sinew",
"skull",
"sky",
"slab",
"slice",
"slit",
"slot",
"slug",
"snail",
"snake",
"snare",
"sniff",
"sock",
"son",
"song",
"sound",
"sparrow",
"spear",
"spearhead",
"spell",
"spider",
"spirit",
"splint",
"splinter",
"spouse",
"spring",
"squirrel",
"stable",
"staff",
"stag",
"stake",
"stalagmite",
"stalk",
"star",
"starling",
"steppe",
"stick",
"stinger",
"stomach",
"stone",
"storeroom",
"stranger",
"stream",
"strike",
"sturgeon",
"summer",
"sun",
"supper",
"surprise",
"swamp",
"swap",
"swan",
"sword",
"table",
"teat",
"temple",
"tent",
"testicle",
"texture",
"thorn",
"thought",
"thread",
"throat",
"tick",
"tile",
"time",
"thing",
"toe",
"tongue",
"tooth",
"tortoise",
"touch",
"tower",
"town",
"trade",
"transformation",
"transition",
"trap",
"tree",
"tribe",
"troop",
"trouser&nbspleg",
"trout",
"trunk",
"tube",
"tune",
"turnip",
"twilight",
"twin",
"udder",
"ulcer",
"uncle",
"unused&nbspland",
"vagina",
"valley",
"village",
"violin",
"voice",
"wagon",
"walk",
"wall",
"wart",
"wasp",
"way",
"weapon",
"weasel",
"wedding",
"wedge",
"weevil",
"well",
"whale",
"wheel",
"whetstone",
"whip",
"wife",
"willow",
"window",
"wing",
"winter",
"wolf",
"woman",
"womb",
"world",
"worm",
"word",
"wort",
"wound",
"year",
"yelp",
"yew",
"yoke",


export {
    countNounArray,
    countNounArrayPlural,
    activePassive,
    animInan,
    divineNonDivine,
    humanAnimalInan,
    mascFemNeut,
    mascFem,
    naturalArtificial,
    animacyClassifierArray,
    shapeClassifierArray,
    shortGenericClassifierArray
}