const countNounArray = [];
const countNounArrayPlural = [];
const activePassive = [];
const animInan = [];
const divineNonDivine= [];
const humanAnimalInan = [];
const mascFemNeut = [];
const mascFem = [];
const naturalArtificial = [];
const animacyClassifierArray = [];
const shapeClassifierArray = [];
const shortGenericClassifierArray = [];

function addWords() {

countNounArray.push("acorn");
countNounArrayPlural.push("acorns");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("affliction");
countNounArrayPlural.push("afflictions");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("alder");
countNounArrayPlural.push("alders");
activePassive.push("passive")
animInan.push("anim");
divineNonDivine.push("divine");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tree");

countNounArray.push("anus");
countNounArrayPlural.push("anuses");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("attack");
countNounArrayPlural.push("attacks");
activePassive.push("active")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("apple");
countNounArrayPlural.push("apples");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("edible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("arch");
countNounArrayPlural.push("arches");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("tool");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("tool");

countNounArray.push("arm");
countNounArrayPlural.push("arms");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("tool");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("army");
countNounArrayPlural.push("armies");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("human");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("man");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("human2");

countNounArray.push("arrow");
countNounArrayPlural.push("arrows");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("tool");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("audience");
countNounArrayPlural.push("audiences");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("human");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("man");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("human2");

countNounArray.push("auger");
countNounArrayPlural.push("augers");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("divine");
humanAnimalInan.push("human");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("man");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("human2");

countNounArray.push("autumn");
countNounArrayPlural.push("autumns");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("divine");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("feminine2");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("axe");
countNounArrayPlural.push("axes");
activePassive.push("active")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("feminine2");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("badger");
countNounArrayPlural.push("badgers");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine2");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("land-animal");

countNounArray.push("bag");
countNounArrayPlural.push("bags");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("feminine2");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("tool");

countNounArray.push("ball");
countNounArrayPlural.push("balls");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("tool");

countNounArray.push("band");
countNounArrayPlural.push("bands");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("human");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("human2");

countNounArray.push("banquet");
countNounArrayPlural.push("banquets");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("bar");
countNounArrayPlural.push("bars");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("barrow");
countNounArrayPlural.push("barrows");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("divine");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("basket");
countNounArrayPlural.push("baskets");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("tool");

countNounArray.push("bead");
countNounArrayPlural.push("beads");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("tool");

countNounArray.push("beak");
countNounArrayPlural.push("beaks");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("beam");
countNounArrayPlural.push("beams");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("bean");
countNounArrayPlural.push("beans");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("edible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("bear");
countNounArrayPlural.push("bears");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("land-animal");

countNounArray.push("beard");
countNounArrayPlural.push("beards");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("beaver");
countNounArrayPlural.push("beavers");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("water-animal");

countNounArray.push("bed");
countNounArrayPlural.push("beds");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("bedroom");
countNounArrayPlural.push("bedrooms");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("tool");

countNounArray.push("bee");
countNounArrayPlural.push("bees");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("flying-animal");

countNounArray.push("beech");
countNounArrayPlural.push("beeches");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("divine");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tree");

countNounArray.push("belt");
countNounArrayPlural.push("belts");
activePassive.push("active");
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("berry");
countNounArrayPlural.push("berries");
activePassive.push("passive");
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("edible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural");

countNounArray.push("bird");
countNounArrayPlural.push("birds");
activePassive.push("active");
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine21");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("flying-animal");

countNounArray.push("birdsong");
countNounArrayPlural.push("birdsongs");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("neuter");
mascFem.push("masculine21");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("blackbird");
countNounArrayPlural.push("blackbirds");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine21");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("bladder");
countNounArrayPlural.push("bladders");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("blade");
countNounArrayPlural.push("blades");
activePassive.push("active")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("blister");
countNounArrayPlural.push("blisters");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("blow");
countNounArrayPlural.push("blows");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("boar");
countNounArrayPlural.push("boars");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("land-animal");

countNounArray.push("board");
countNounArrayPlural.push("boards");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("flat");
shortGenericClassifierArray.push("tool");

countNounArray.push("boat");
countNounArrayPlural.push("boats");
activePassive.push("active")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("body");
countNounArrayPlural.push("bodies");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("bolt");
countNounArrayPlural.push("bolts");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("bone");
countNounArrayPlural.push("bones");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("book");
countNounArrayPlural.push("books");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("boot");
countNounArrayPlural.push("boots");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("bottom");
countNounArrayPlural.push("bottoms");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("boulder");
countNounArrayPlural.push("boulders");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("bow");
countNounArrayPlural.push("bows");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("naturaartificiall");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("bowl");
countNounArrayPlural.push("bowls");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("tool");

countNounArray.push("bowstring");
countNounArrayPlural.push("bowstrings");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("bracelet");
countNounArrayPlural.push("bracelets");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("tool");

countNounArray.push("brain");
countNounArrayPlural.push("brains");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("branch");
countNounArrayPlural.push("branches");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("breast");
countNounArrayPlural.push("breasts");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("breath");
countNounArrayPlural.push("breaths");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("divine");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("bristle");
countNounArrayPlural.push("bristles");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("brother");
countNounArrayPlural.push("brothers");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("human");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("man");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("human2");

countNounArray.push("brow");
countNounArrayPlural.push("brows");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("inan");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("buck");
countNounArrayPlural.push("bucks");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("land-animal");

countNounArray.push("bucket");
countNounArrayPlural.push("buckets");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("inan");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("tool");

countNounArray.push("buffet");
countNounArrayPlural.push("buffets");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("inan");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("edible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("building");
countNounArrayPlural.push("buildings");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("inan");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("bull");
countNounArrayPlural.push("bulls");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("meat");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("land-animal");

countNounArray.push("bump");
countNounArrayPlural.push("bumps");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("burden");
countNounArrayPlural.push("burdens");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("butterfly");
countNounArrayPlural.push("butterflies");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("feminine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("flat");
shortGenericClassifierArray.push("flying-animal");

countNounArray.push("cabin");
countNounArrayPlural.push("cabins");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("feminine2");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("tool");

countNounArray.push("cage");
countNounArrayPlural.push("cages");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("tool");

countNounArray.push("carp");
countNounArrayPlural.push("carps");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("feminine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("water-animal");

countNounArray.push("carrot");
countNounArrayPlural.push("carrots");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("inan");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("edible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("cat");
countNounArrayPlural.push("cats");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("anim");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("land-animal");

countNounArray.push("cauldron");
countNounArrayPlural.push("cauldrons");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("divine");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("tool");

countNounArray.push("cave");
countNounArrayPlural.push("caves");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("cavity");
countNounArrayPlural.push("cavities");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("cedar");
countNounArrayPlural.push("cedars");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("divine");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("cell");
countNounArrayPlural.push("cells");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("tool");

countNounArray.push("change");
countNounArrayPlural.push("changes");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("chariot");
countNounArrayPlural.push("chariots");
activePassive.push("active")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("tool");

countNounArray.push("cherry");
countNounArrayPlural.push("cherries");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("edible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("chicken");
countNounArrayPlural.push("chickens");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("meat");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("chickpea");
countNounArrayPlural.push("chickpeas");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("edible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("child");
countNounArrayPlural.push("children");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("human");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("child");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("human2");

countNounArray.push("chin");
countNounArrayPlural.push("chins");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("circle");
countNounArrayPlural.push("circles");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("clan");
countNounArrayPlural.push("clans");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("man");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("cliff");
countNounArrayPlural.push("cliffs");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("cloak");
countNounArrayPlural.push("cloaks");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("cloud");
countNounArrayPlural.push("clouds");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("club");
countNounArrayPlural.push("clubs");
activePassive.push("active")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("coin");
countNounArrayPlural.push("coins");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("tool");

countNounArray.push("column");
countNounArrayPlural.push("columns");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("confession");
countNounArrayPlural.push("confessions");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("coot");
countNounArrayPlural.push("coots");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("water-animal");

countNounArray.push("corner");
countNounArrayPlural.push("corner");
activePassive.push("passive")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("council");
countNounArrayPlural.push("councils");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("man");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("human2");

countNounArray.push("cow");
countNounArrayPlural.push("cows");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("feminine2");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("meat");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("land-animal");

countNounArray.push("cowherd");
countNounArrayPlural.push("cowherds");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("human");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("man");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("human2");

countNounArray.push("crab");
countNounArrayPlural.push("crabs");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("feminine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("flat");
shortGenericClassifierArray.push("water-animal");

countNounArray.push("craftsman");
countNounArrayPlural.push("craftsmen");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("man");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("human2");

countNounArray.push("crane");
countNounArrayPlural.push("cranes");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("feminine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("flying-animal");

countNounArray.push("crease");
countNounArrayPlural.push("creases");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("crime");
countNounArrayPlural.push("crimes");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");        

countNounArray.push("crow");
countNounArrayPlural.push("crows");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("feminine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("flying-animal");

countNounArray.push("crowd");
countNounArrayPlural.push("crowds");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("human");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("man");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("human2");

countNounArray.push("cuckoo");
countNounArrayPlural.push("cuckoos");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("flying-animal");

countNounArray.push("cup");
countNounArrayPlural.push("cups");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("divine");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("tall-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("curve");
countNounArrayPlural.push("curves");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("curved&nbspbeam");
countNounArrayPlural.push("curved&nbspbeams");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("custom");
countNounArrayPlural.push("customs");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("femininneutere2");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("daughter");
countNounArrayPlural.push("daughters");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("human");
mascFemNeut.push("feminine2");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("child");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("human2");

countNounArray.push("dawn");
countNounArrayPlural.push("dawns");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("divine");
humanAnimalInan.push("inan");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("day");
countNounArrayPlural.push("days");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("divine");
humanAnimalInan.push("inan");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("deer");
countNounArrayPlural.push("deer");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("land-animal");

countNounArray.push("dent");
countNounArrayPlural.push("dents");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("dice");
countNounArrayPlural.push("die");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("divine");
humanAnimalInan.push("inan");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("tool");

countNounArray.push("dinner");
countNounArrayPlural.push("dinners");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("inan");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("edible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("dip");
countNounArrayPlural.push("dips");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("inan");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("direction");
countNounArrayPlural.push("directions");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("inan");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("ditch");
countNounArrayPlural.push("ditches");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("inan");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("dog");
countNounArrayPlural.push("dogs");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("labour");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("land-animal");

countNounArray.push("dolphin");
countNounArrayPlural.push("dolphins");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("water-animal");

countNounArray.push("donkey");
countNounArrayPlural.push("donkeys");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("labour");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("land-animal");

countNounArray.push("door");
countNounArrayPlural.push("doors");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("flat");
shortGenericClassifierArray.push("tool");

countNounArray.push("doorjam");
countNounArrayPlural.push("doorjams");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("flat");
shortGenericClassifierArray.push("tool");

countNounArray.push("dormouse");
countNounArrayPlural.push("dormice");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("feminine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("land-animal");

countNounArray.push("dorsal&nbspfin");
countNounArrayPlural.push("dorsal&nbspfins");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine2");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("flat");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("dragon");
countNounArrayPlural.push("dragons");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("divine");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("flying-animal");

countNounArray.push("drop");
countNounArrayPlural.push("drops");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("edible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("duck");
countNounArrayPlural.push("ducks");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("feminine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("water-animal");

countNounArray.push("eagle");
countNounArrayPlural.push("eagles");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("flying-animal");

countNounArray.push("ear");
countNounArrayPlural.push("ears");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("flat");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("edge");
countNounArrayPlural.push("edges");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("flat");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("eel");
countNounArrayPlural.push("eels");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("feminine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("water-animal");

countNounArray.push("egg");
countNounArrayPlural.push("eggs");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine2");
naturalArtificial.push("natural");
animacyClassifierArray.push("edible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("elbow");
countNounArrayPlural.push("elbows");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine2");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("elk");
countNounArrayPlural.push("elks");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("land-animal");

countNounArray.push("elm");
countNounArrayPlural.push("elms");
activePassive.push("passive")
animInan.push("anim");
divineNonDivine.push("divine");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("tree");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("embrace");
countNounArrayPlural.push("embraces");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("emotion");
countNounArrayPlural.push("emotions");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("enclosure");
countNounArrayPlural.push("enclosures");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("tool");

countNounArray.push("enemy");
countNounArrayPlural.push("enemies");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("human");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("man");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("human2");

countNounArray.push("estuary");
countNounArrayPlural.push("estuaries");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("man");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("ewe");
countNounArrayPlural.push("ewes");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("feminine2");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("fur");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("land-animal");

countNounArray.push("exchange");
countNounArrayPlural.push("exchanges");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("eye");
countNounArrayPlural.push("eyes");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("eyebrow");
countNounArrayPlural.push("eyebrows");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("face");
countNounArrayPlural.push("faces");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("falcon");
countNounArrayPlural.push("falcons");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("flying-animal");

countNounArray.push("family");
countNounArrayPlural.push("families");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("human");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("man");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("human2");

countNounArray.push("father");
countNounArrayPlural.push("fathers");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("human");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("man");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("human2");

countNounArray.push("favour");
countNounArrayPlural.push("favours");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("feast");
countNounArrayPlural.push("feasts");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("edible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("fence");
countNounArrayPlural.push("fences");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("festival");
countNounArrayPlural.push("festivals");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("divine");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("field");
countNounArrayPlural.push("fields");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("finger");
countNounArrayPlural.push("fingers");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("fir");
countNounArrayPlural.push("firs");
activePassive.push("passive")
animInan.push("anim");
divineNonDivine.push("divine");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("tree");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("fire");
countNounArrayPlural.push("fires");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("divine");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("fish");
countNounArrayPlural.push("fish");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("water-animal");

countNounArray.push("fist");
countNounArrayPlural.push("fists");
activePassive.push("active")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("flock");
countNounArrayPlural.push("flocks");
activePassive.push("passive")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("floor");
countNounArrayPlural.push("floors");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("flat");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("flower");
countNounArrayPlural.push("flowers");
activePassive.push("passive")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("fly");
countNounArrayPlural.push("flies");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("feminine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("flying-animal");

countNounArray.push("fold");
countNounArrayPlural.push("folds");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("foot");
countNounArrayPlural.push("feet");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("footprint");
countNounArrayPlural.push("footprints");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("forearm");
countNounArrayPlural.push("forearms");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("forehead");
countNounArrayPlural.push("foreheads");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("flat");
shortGenericClassifierArray.push("natural-inanimate")

countNounArray.push("forest");
countNounArrayPlural.push("forests");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("divine");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("tree");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate")

countNounArray.push("fork");
countNounArrayPlural.push("forks");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("divine");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool")

countNounArray.push("fort");
countNounArrayPlural.push("forts");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("tool")

countNounArray.push("fortification");
countNounArrayPlural.push("fortifications");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("tool")

countNounArray.push("freeman");
countNounArrayPlural.push("freemen");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("human");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("man");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("human2")

countNounArray.push("friend");
countNounArrayPlural.push("friends");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("human");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("man");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("human2")

countNounArray.push("frog");
countNounArrayPlural.push("frogs");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("feminine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("water-animal")

countNounArray.push("frog");
countNounArrayPlural.push("frogs");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("feminine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("water-animal")

countNounArray.push("furrow");
countNounArrayPlural.push("furrows");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("gate");
countNounArrayPlural.push("gates");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("genocide");
countNounArrayPlural.push("genocides");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("gift");
countNounArrayPlural.push("gifts");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("tool");

countNounArray.push("girl");
countNounArrayPlural.push("girls");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("human");
mascFemNeut.push("feminine2");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("woman");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("human2");

countNounArray.push("gland");
countNounArrayPlural.push("glands");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("glove");
countNounArrayPlural.push("gloves");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("flat");
shortGenericClassifierArray.push("tool");

countNounArray.push("gnat");
countNounArrayPlural.push("gnats");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("flying-animal");

countNounArray.push("goat");
countNounArrayPlural.push("goats");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("meat");
shapeClassifierArray.push("short-and-wide");
shortGenericClassifierArray.push("land-animal");

countNounArray.push("god");
countNounArrayPlural.push("gods");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("divine");
humanAnimalInan.push("human");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("man");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("human2");

countNounArray.push("goose");
countNounArrayPlural.push("geese");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("feminine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("flying-animal");

countNounArray.push("gosling");
countNounArrayPlural.push("goslings");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("animal");
mascFemNeut.push("feminine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("flying-animal");

countNounArray.push("grain");
countNounArrayPlural.push("grains");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("edible");
shapeClassifierArray.push("round");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("granddaughter");
countNounArrayPlural.push("granddaughters");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("feminine2");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("child");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("human2");

countNounArray.push("grandson");
countNounArrayPlural.push("grandsons");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("child");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("human2");

countNounArray.push("grave");
countNounArrayPlural.push("graves");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("divine");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("groove");
countNounArrayPlural.push("grooves");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("grunt");
countNounArrayPlural.push("grunts");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("shapeless");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("guest");
countNounArrayPlural.push("guests");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("masculine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("man");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("human2");

countNounArray.push("guitar");
countNounArrayPlural.push("guitars");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("artificial");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("tool");

countNounArray.push("gull");
countNounArrayPlural.push("gulls");
activePassive.push("active")
animInan.push("anim");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("feminine2");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("wild-animal");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("flying-animal");

countNounArray.push("gullet");
countNounArrayPlural.push("gullets");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("masculine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("gulley");
countNounArrayPlural.push("gulleys");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

countNounArray.push("gum");
countNounArrayPlural.push("gums");
activePassive.push("passive")
animInan.push("inan");
divineNonDivine.push("profane");
humanAnimalInan.push("secondinanimate");
mascFemNeut.push("neuter");
mascFem.push("feminine1");
naturalArtificial.push("natural");
animacyClassifierArray.push("inedible");
shapeClassifierArray.push("long-and-slender");
shortGenericClassifierArray.push("natural-inanimate");

"hall",
"hammer",
"hand",
"handle",
"hare",
"harp",
"hat",
"hawk",
"hawthorn",
"hazel",
"head",
"heart",
"hearth",
"hedgehog",
"height",
"henbane",
"herd",
"hill",
"hip",
"hole",
"home",
"honour",
"hoof",
"hook",
"horn",
"hornet",
"horse",
"horsefly",
"house",
"howl",
"hug",
"human",
"husband",
"icicle",
"insect",
"javelin",
"jaw",
"jay",
"jewel",
"journey",
"juniper",
"kernel",
"kidney",
"king",
"kiss",
"kitten",
"knee",
"knife",
"knuckle",
"lake",
"lamb",
"land",
"language",
"leaf",
"leech",
"leg",
"lever",
"limb",
"lineage",
"lion",
"lip",
"liver",
"log",
"lord",
"louse",
"lung",
"lynx",
"mace",
"maggot",
"magpie",
"mallet",
"mammoth",
"man",
"mane",
"map",
"maple",
"mare",
"married&nbspcouple",
"marsh",
"marten",
"massacre",
"master",
"meadow",
"meeting",
"membrane",
"memory",
"mistress",
"moon",
"mother",
"mountain",
"mouse",
"mouth",
"mussel",
"nail",
"name",
"navel",
"neck",
"necklace",
"needle",
"nest",
"net",


"nettle",
"night",
"noon",
"nose",
"notch",
"oak",
"oar",
"oath",
"onion",
"origin",
"orphan",
"otter",
"owl",
"ox",
"page",
"palm",
"pasture",
"path",
"paw",
"pea",
"pebble",
"peg",
"pendant",
"penis",
"perch",
"person",
"phantom",
"pick",
"pig",
"piglet",
"pike",
"pillar",
"pin",
"pit",
"place",
"plank",
"plough",
"poem",
"poet",
"point",
"pole",
"polecat",
"pool",
"poppy",
"post",
"pot",
"prayer",
"priest",
"projection",
"proverb",
"puppy",
"purchase",
"rag",
"ram",
"raven",
"ravine",
"razor",
"realm",
"reed",
"relation",
"relationship",
"rhythm",
"rib",
"right",
"ring",
"river",
"riverbank",
"road",
"rock",
"rod",
"roof",
"rooster",
"root",
"route",
"row",
"rule",
"salmon",
"saying",
"scent",
"scythe",
"sea",
"seal",
"season",
"seat",
"seed",
"serpent",
"servant",
"shaft",
"shark",
"sheep",
"sheet",
"shelf",
"shell",
"shield",
"shoe",
"shoulder",
"shroud",
"sieve",
"sign",
"sinew",
"skull",
"sky",
"slab",
"slice",
"slit",
"slot",
"slug",
"snail",
"snake",
"snare",
"sniff",
"sock",
"son",
"song",
"sound",
"sparrow",
"spear",
"spearhead",
"spell",
"spider",
"spirit",
"splint",
"splinter",
"spouse",
"spring",
"squirrel",
"stable",
"staff",
"stag",
"stake",
"stalagmite",
"stalk",
"star",
"starling",
"steppe",
"stick",
"stinger",
"stomach",
"stone",
"storeroom",
"stranger",
"stream",
"strike",
"sturgeon",
"summer",
"sun",
"supper",
"surprise",
"swamp",
"swap",
"swan",
"sword",
"table",
"teat",
"temple",
"tent",
"testicle",
"texture",
"thorn",
"thought",
"thread",
"throat",
"tick",
"tile",
"time",
"thing",
"toe",
"tongue",
"tooth",
"tortoise",
"touch",
"tower",
"town",
"trade",
"transformation",
"transition",
"trap",
"tree",
"tribe",
"troop",
"trouser&nbspleg",
"trout",
"trunk",
"tube",
"tune",
"turnip",
"twilight",
"twin",
"udder",
"ulcer",
"uncle",
"unused&nbspland",
"vagina",
"valley",
"village",
"violin",
"voice",
"wagon",
"walk",
"wall",
"wart",
"wasp",
"way",
"weapon",
"weasel",
"wedding",
"wedge",
"weevil",
"well",
"whale",
"wheel",
"whetstone",
"whip",
"wife",
"willow",
"window",
"wing",
"winter",
"wolf",
"woman",
"womb",
"world",
"worm",
"word",
"wort",
"wound",
"year",
"yelp",
"yew",
"yoke",
}

let generateLanguageButton = document.getElementById("generate-language");
generateLanguageButton.addEventListener("click", addWords);


export {
    countNounArray,
    countNounArrayPlural,
    activePassive,
    animInan,
    divineNonDivine,
    humanAnimalInan,
    mascFemNeut,
    mascFem,
    naturalArtificial,
    animacyClassifierArray,
    shapeClassifierArray,
    shortGenericClassifierArray
}