const pluralSingulativeMassNounArray = [
    "wiffs of air",
    "drops of blood",
    "chunks of bronze",
    "handfuls of dirt",
    "bits of dust",
    "clumps of clay",
    "dollops of cream",
    "chunks of copper",
    "bits of fog",
    "chunks of gold",
    "blades of grass",
    "chunks of ice",
    "chunks of iron",
    "cuts of meat",
    "drops of milk",
    "clumps of mud",
    "raindrops",
    "drops of saliva",
    "grains of sand",
    "portions of sauce",
    "wisps of smoke",
    "wisps of steam",
    "beads of sweat",
    "drops of water",
    "gusts of wind",
    "glasses of wine",
]

export default pluralSingulativeMassNounArray;