const singulativeMassNounArray = [
    "wiff&nbspof&nbspair",
    "drop&nbspof&nbspblood",
    "chunk&nbspof&nbspbronze",
    "handful&nbspof&nbspdirt",
    "bit&nbspof&nbspdust",
    "clump&nbspof&nbspclay",
    "dollop&nbspof&nbspcream",
    "chunk&nbspof&nbspcopper",
    "bit&nbspof&nbspfog",
    "chunk&nbspof&nbspgold",
    "blade&nbspof&nbspgrass",
    "chunk&nbspof&nbspice",
    "chunk&nbspof&nbspiron",
    "cut&nbspof&nbspmeat",
    "drop&nbspof&nbspmilk",
    "clump&nbspof&nbspmud",
    "raindrop",
    "drop&nbspof&nbspsaliva",
    "grain&nbspof&nbspsand",
    "portion&nbspof&nbspsauce",
    "wisp&nbspof&nbspsmoke",
    "wisp&nbspof&nbspsteam",
    "bead&nbspof&nbspsweat",
    "drop&nbspof&nbspwater",
    "gust&nbspof&nbspwind",
    "glass&nbspof&nbspwine",
]

export default singulativeMassNounArray;