const singulativeMassNounArray = [
    "wiff of air",
    "drop of blood",
    "chunk of bronze",
    "handful of dirt",
    "bit of dust",
    "clump of clay",
    "dollop of cream",
    "chunk of copper",
    "bit of fog",
    "chunk of gold",
    "blade of grass",
    "chunk of ice",
    "chunk of iron",
    "cut of meat",
    "drop of milk",
    "clump of mud",
    "raindrop",
    "drop of saliva",
    "grain of sand",
    "portion of sauce",
    "wisp of smoke",
    "wisp of steam",
    "bead of sweat",
    "drop of water",
    "gust of wind",
    "glass of wine",
]

export default singulativeMassNounArray;