const animacyClassifierMassArray = [
    "inedible",
    "edible",
    "edible",
    "inedible",
    "inedible",
    "inedible",
    "inedible",
    "edible",
    "inedible",
    "inedible",
    "inedible",
    "inedible",
    "inedible",
    "inedible",
    "inedible",
    "edible",
    "edible",
    "edible",
    "inedible",
    "inedible",
    "inedible",
    "inedible",
    "inedible",
    "inedible",
    "edible",
    "inedible",
    "inedible",
    "inedible",
    "inedible",
    "inedible",
    "edible",
    "inedible",
    "edible",
]

export default animacyClassifierMassArray;