const shapeClassifierMassArray = [
"shapeless",
"shapeless",
"shapeless",
"shapeless",
"shapeless",
"shapeless",
"shapeless",
"shapeless",
"shapeless",
"shapeless",
"long-and-slender",
"shapeless",
"shapeless",
"shapeless",
"shapeless",
"shapeless",
"shapeless",
"shapeless",
"shapeless",
"shapeless",
"shapeless",
"shapeless",
"shapeless",
"shapeless",
"shapeless",
"shapeless",
"shapeless",
"shapeless",
"shapeless",
]

export default shapeClassifierMassArray;