const shortGenericClassifierMassArray = [
"natural-inanimate",
"liquid",
"tool",
"tool",
"natural-inanimate",
"natural-inanimate",
"natural-inanimate",
"natural-inanimate",
"tool",
"natural-inanimate",
"tool",
"grass",
"natural-inanimate",
"tool",
"human2",
"tool",
"natural-inanimate",
"liquid",
"natural-inanimate",
"tool",
"liquid",
"tool",
"liquid",
"natural-inanimate",
"liquid",
"natural-inanimate",
"natural-inanimate",
"liquid",
"tool",
"tool",
"liquid",
"liquid",
"natural-inanimate",
"liquid",
]

export default shortGenericClassifierMassArray;