const activePassiveMass = [
    "passive",
    "passive",
    "passive",
    "passive",
    "passive",
    "passive",
    "passive",
    "passive",
    "active",
    "passive",
    "passive",
    "passive",
    "passive",
    "passive",
    "passive",
    "passive",
    "passive",
    "active",
    "passive",
    "passive",
    "passive",
    "passive",
    "active",
    "active",
    "passive",
    "passive",
    "active",
    "passive",
]

export default activePassiveMass;