const divineNonDivineMass = [
    "profane",
    "profane",
    "divine",
    "profane",
    "profane",
    "profane",
    "profane",
    "divine",
    "profane",
    "divine",
    "profane",
    "profane",
    "divine",
    "profane",
    "profane",
    "profane",
    "profane",
    "profane",
    "profane",
    "profane",
    "profane",
    "profane",
    "profane",
    "divine",
    "profane",
    "divine",
]

export default divineNonDivineMass;