const humanAnimalInanMass = [
    "secondinanimate",
    "secondinanimate",
    "secondinanimate",
    "secondinanimate",
    "secondinanimate",
    "secondinanimate",
    "secondinanimate",
    "secondinanimate",
    "secondinanimate",
    "secondinanimate",
    "secondinanimate",
    "secondinanimate",
    "secondinanimate",
    "secondinanimate",
    "secondinanimate",
    "secondinanimate",
    "secondinanimate",
    "secondinanimate",
    "secondinanimate",
    "secondinanimate",
    "secondinanimate",
    "secondinanimate",
    "secondinanimate",
    "secondinanimate",
    "secondinanimate",
    "secondinanimate",
    "secondinanimate",
]

export default humanAnimalInanMass;