const mascFemMass = [
    "feminine1",
    "masculine1",
    "masculine1",
    "masculine1",
    "feminine1",
    "feminine1",
    "feminine1",
    "masculine1",
    "masculine1",
    "masculine1",
    "feminine1",
    "masculine1",
    "masculine1",
    "masculine1",
    "feminine1",
    "masculine1",
    "masculine1",
    "feminine1",
    "feminine1",
    "feminine1",
    "feminine1",
    "feminine1",
    "feminine1",
    "masculine1",
    "masculine1",
    "feminine1",    
]

export default mascFemMass;