const naturalArtificialMass = [
    "natural",
    "natural",
    "artificial",
    "artificial",
    "natural",
    "natural",
    "natural",
    "natural",
    "natural",
    "natural",
    "natural",
    "natural",
    "natural",
    "natural",
    "natural",
    "artificial",
    "natural",
    "natural",
    "natural",
    "natural",
    "natural",
    "artificial",
    "natural",
    "natural",
    "artificial",
    "natural",
    "natural",
    "natural",
    "natural",
    "artificial",
    "natural",
    "natural",
    "natural",
    "artificial",
]

export default naturalArtificialMass;